package com.example.jiaojiejia.googlephoto.greendao;

import com.example.jiaojiejia.googlephoto.bean.BaseModule;
import com.example.jiaojiejia.googlephoto.bean.PhotoModule;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig baseModuleDaoConfig;
    private final DaoConfig photoModuleDaoConfig;

    private final BaseModuleDao baseModuleDao;
    private final PhotoModuleDao photoModuleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        baseModuleDaoConfig = daoConfigMap.get(BaseModuleDao.class).clone();
        baseModuleDaoConfig.initIdentityScope(type);

        photoModuleDaoConfig = daoConfigMap.get(PhotoModuleDao.class).clone();
        photoModuleDaoConfig.initIdentityScope(type);

        baseModuleDao = new BaseModuleDao(baseModuleDaoConfig, this);
        photoModuleDao = new PhotoModuleDao(photoModuleDaoConfig, this);

        registerDao(BaseModule.class, baseModuleDao);
        registerDao(PhotoModule.class, photoModuleDao);
    }
    
    public void clear() {
        baseModuleDaoConfig.clearIdentityScope();
        photoModuleDaoConfig.clearIdentityScope();
    }

    public BaseModuleDao getBaseModuleDao() {
        return baseModuleDao;
    }

    public PhotoModuleDao getPhotoModuleDao() {
        return photoModuleDao;
    }

}
