package com.example.jiaojiejia.googlephoto.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.jiaojiejia.googlephoto.bean.PhotoModule;
import com.example.jiaojiejia.googlephoto.bean.BaseModule;

import com.example.jiaojiejia.googlephoto.greendao.PhotoModuleDao;
import com.example.jiaojiejia.googlephoto.greendao.BaseModuleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig photoModuleDaoConfig;
    private final DaoConfig baseModuleDaoConfig;

    private final PhotoModuleDao photoModuleDao;
    private final BaseModuleDao baseModuleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        photoModuleDaoConfig = daoConfigMap.get(PhotoModuleDao.class).clone();
        photoModuleDaoConfig.initIdentityScope(type);

        baseModuleDaoConfig = daoConfigMap.get(BaseModuleDao.class).clone();
        baseModuleDaoConfig.initIdentityScope(type);

        photoModuleDao = new PhotoModuleDao(photoModuleDaoConfig, this);
        baseModuleDao = new BaseModuleDao(baseModuleDaoConfig, this);

        registerDao(PhotoModule.class, photoModuleDao);
        registerDao(BaseModule.class, baseModuleDao);
    }
    
    public void clear() {
        photoModuleDaoConfig.clearIdentityScope();
        baseModuleDaoConfig.clearIdentityScope();
    }

    public PhotoModuleDao getPhotoModuleDao() {
        return photoModuleDao;
    }

    public BaseModuleDao getBaseModuleDao() {
        return baseModuleDao;
    }

}
